_BASE_: "../../Base-baseline.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 751

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

INPUT:
  DO_AUTOAUG: True

OUTPUT_DIR: "logs/ablation/new/Market1501/AOTUAUG_baseline"
