_BASE_: "../../Base-baseline.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 751

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: 101
    PRETRAIN_PATH: "/public/home/yuchangbingroup/feiyuejiao/.cache/torch/checkpoints/resnet101_ibn_a.pth"

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/ablation/Market1501/baseline_R101"
