_BASE_: "../../Base-baseline.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 751

  BACKBONE:
    NORM: "syncBN"

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/ablation/new/Market1501/BN_baseline"
