_BASE_: "../../Base-baseline.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 751

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

INPUT:
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]

OUTPUT_DIR: "logs/ablation/new/Market1501/REA_baseline"
