_BASE_: "../Base-AGW.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
    WITH_IBN: True
    PRETRAIN_PATH: "/public/home/yuchangbingroup/feiyuejiao/.cache/torch/checkpoints/resnet50_ibn_a.pth"

  HEADS:
    NUM_CLASSES: 751


DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/market1501/agw_R50-ibn"
