_BASE_: "../Base-bagtricks.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 751
    NORM: "syncBN"
  BACKBONE:
    NORM: "syncBN"

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

INPUT:
  REA:
    ENABLED: False

OUTPUT_DIR: "logs/market1501/bagtricks_R50_wo_era"
