_BASE_: "../Base-MGN.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True # fei
    NORM: "syncBN"
    PRETRAIN_PATH: "/public/home/yuchangbingroup/feiyuejiao/.cache/torch/checkpoints/resnet50_ibn_a.pth"
  HEADS:
    NUM_CLASSES: 751
    NORM: "syncBN"

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)


OUTPUT_DIR: "logs/market/mgn_R50-ibn"
