_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN_PATH: "/public/home/yuchangbingroup/feiyuejiao/.cache/torch/checkpoints/resnet50_ibn_a.pth"
    NORM: "syncBN"
  HEADS:
    NUM_CLASSES: 751
    NORM: "syncBN"

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

TEST:
  EVAL_PERIOD: 2000
  PRECISE_BN:
    DATASET: 'Market1501'

OUTPUT_DIR: "logs/market1501/sbs_R50-ibn"
