_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    NORM: "syncBN"
  HEADS:
    NORM: "syncBN"
    NUM_CLASSES: 751

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

TEST:
  PRECISE_BN:
    DATASET: 'Market1501'

OUTPUT_DIR: "logs/market1501/sbs_R50"
