_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: 101
    WITH_IBN: True
    PRETRAIN_PATH: "/public/home/yuchangbingroup/feiyuejiao/.cache/torch/checkpoints/resnet101_ibn_a.pth"
    NORM: "syncBN"

  HEADS:
    NUM_CLASSES: 751
    NORM: "syncBN"

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

TEST:
  PRECISE_BN:
    DATASET: 'Market1501'

OUTPUT_DIR: "logs/market1501/sbs-R101-ibn"
