_BASE_: "../Base-MGN.yml"

MODEL:
  BACKBONE:
    PRETRAIN_PATH: "/public/home/yuchangbingroup/feiyuejiao/.cache/torch/checkpoints/resnet50_ibn_a.pth"
  HEADS:
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)


OUTPUT_DIR: "logs/dukemtmc/mgn_R50-ibn"
