_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN_PATH: "/public/home/yuchangbingroup/feiyuejiao/.cache/torch/checkpoints/resnet50_ibn_a.pth"

  HEADS:
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

TEST:
  EVAL_PERIOD: 2000
  PRECISE_BN:
    DATASET: 'DukeMTMC'

OUTPUT_DIR: "logs/dukemtmc/sbs_R50-ibn"
