_BASE_: "../../Base-baseline.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 702

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: 101
    PRETRAIN_PATH: "/public/home/yuchangbingroup/feiyuejiao/.cache/torch/checkpoints/resnet101_ibn_a.pth"

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "logs/ablation/DukeMTMC/baseline_R101"
