_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN_PATH: "/public/home/yuchangbingroup/feiyuejiao/.cache/torch/checkpoints/resnet50_ibn_a.pth"

  HEADS:
    NUM_CLASSES: 1041

SOLVER:
  MAX_ITER: 42000
  STEPS: [19000, 33000]
  WARMUP_ITERS: 4700
  CHECKPOINT_PERIOD: 5000

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

TEST:
  EVAL_PERIOD: 5000

OUTPUT_DIR: "logs/msmt17/bagtricks_R50-ibn"

